version: '3.9'

services:
  portellaweb:
    build: .
    image: portella-web
    container_name: portella-web
    ports:
      - "5000:5000"  # expõe a porta do Gunicorn
    networks:
      - metanet1
      - nginxmaneger
    restart: always
    environment:
      - ENV=production

networks:
  metanet1:
    external: true
  nginxmaneger:
    external: true
